version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
#version: '3'
#
#networks:
#    laravel:
#
#
#services:
#    app:
#        build:
#            context: ./dockerfiles
#            dockerfile: nginx.dockerfile
#        ports:
#            - "8080:80"
#        volumes:
#            - ./:/var/www
#        depends_on:
#            - php
#            - redis
#            - mysql
#        networks:
#            - laravel
#        logging:
#            options:
#                max-size: 10m
#                max-file: "5"
#
#    mysql:
#        image: mariadb:10.6
#        restart: unless-stopped
#        tty: true
#        ports:
#            - "3360:3306"
#        environment:
#            MYSQL_DATABASE: '${DB_DATABASE}'
#            MYSQL_USER: '${DB_USERNAME}'
#            MYSQL_PASSWORD: '${DB_PASSWORD}'
#            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
#        networks:
#            - laravel
#        logging:
#            options:
#                max-size: 10m
#                max-file: "5"
#
#    php:
#        user: 'www-data:www-data'
#        build:
#            context: ./dockerfiles
#            dockerfile: php.dockerfile
#        ports:
#            - "9000:8999"
#        volumes:
#            - ./:/var/www
#        networks:
#            - laravel
#        logging:
#            options:
#                max-size: 10m
#                max-file: "5"
#
#    redis:
#        image: redis:alpine
#        restart: unless-stopped
#        ports:
#            - "6399:6379"
#        networks:
#            - laravel
#        logging:
#            options:
#                max-size: 10m
#                max-file: "5"
